### ISSUE TITLE
2024年5月21日运行出错

### ISSUE THREAD

**Issue by lenewing3** [Yumu152068/aliyun-auto-signin#1]
下面截取的是Actions运行时报的python错误。

`Traceback (most recent call last):
  File "/home/runner/work/aliyun-signin-action/aliyun-signin-action/release/aliyun-auto-signin-1.0.2/app.py", line 446, in <module>
    main()
  File "/home/runner/work/aliyun-signin-action/aliyun-signin-action/release/aliyun-auto-signin-1.0.2/app.py", line 412, in main
    results.append(signin.run())
  File "/home/runner/work/aliyun-signin-action/aliyun-signin-action/release/aliyun-auto-signin-1.0.2/app.py", line 243, in run
    self.__sign_in()
  File "/home/runner/work/aliyun-signin-action/aliyun-signin-action/release/aliyun-auto-signin-1.0.2/app.py", line 168, in __sign_in
    if not data['result']
KeyError: 'result'
Error: Process completed with exit code 1.`

**Comment by Carnia** [comment]
阿里云盘新增了请求头做验签，应该是无法再用web端接口签到了

https://github.com/mrabit/aliyundriveDailyCheck
